SPECIES_PROFILES = {
    "Bass": {
        "best_months": [6, 7, 8, 9],
        "good_times": ["dawn", "dusk", "night"],
        "cloud_range": (50, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (8, 28),
        "good_wind_directions": ["SW", "W", "NW"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (12, 24),
        "pressure_range": (995, 1018),
        "clarity": "slightly_coloured",
        "likes_moving_water": True,
        "method": "Spinning with soft plastics, metals, shallow divers or a Toby. Focus on moving tide, gullies, surf edges and low light.",
    },

    "Flounder": {
        "best_months": [5, 6, 7, 8, 9, 10, 11],
        "good_times": ["day", "dusk"],
        "cloud_range": (0, 70),
        "rain_range": (0, 2),
        "wind_speed_range": (3, 22),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (7, 22),
        "pressure_range": (1000, 1025),
        "clarity": "slightly_coloured",
        "likes_moving_water": True,
        "method": "Light ledgering with ragworm, lugworm or small fish baits. Fish the flooding or ebbing tide where food is being pushed along.",
    },

    "Sea Trout": {
        "best_months": [6, 7, 8, 9],
        "good_times": ["dusk", "night"],
        "cloud_range": (60, 100),
        "rain_range": (0, 3),
        "wind_speed_range": (5, 25),
        "good_wind_directions": ["SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (8, 18),
        "pressure_range": (995, 1018),
        "clarity": "falling_and_clearing",
        "likes_moving_water": True,
        "method": "Small spinners, small plugs or night fly fishing. Best after fresh water when the river is clearing and into darkness.",
    },

    "Mullet": {
        "best_months": [6, 7, 8, 9],
        "good_times": ["day"],
        "cloud_range": (0, 60),
        "rain_range": (0, 0.5),
        "wind_speed_range": (0, 14),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["N", "NE", "E"],
        "temperature_range": (14, 26),
        "pressure_range": (1008, 1030),
        "clarity": "clear",
        "likes_moving_water": False,
        "method": "Float fish bread, small baits or surface bread in calm, warm, clear conditions. Avoid heavy colour and rough water.",
    },

    "Brown Trout": {
        "best_months": [4, 5, 6, 7],
        "good_times": ["dawn", "dusk"],
        "cloud_range": (40, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (3, 24),
        "good_wind_directions": ["SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (7, 18),
        "pressure_range": (995, 1020),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Dry fly, nymphs, spiders or small upstream lures. In low clear water, fish lighter and later in the evening.",
    },

    "Salmon": {
        "best_months": [7, 8, 9, 10],
        "good_times": ["dawn", "dusk"],
        "cloud_range": (50, 100),
        "rain_range": (0, 4),
        "wind_speed_range": (3, 28),
        "good_wind_directions": ["SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (6, 18),
        "pressure_range": (990, 1018),
        "clarity": "falling_and_clearing",
        "likes_moving_water": True,
        "method": "Fly or spinner depending on water height. Best after a lift in river level when the river is fining down.",
    },

    "Rainbow Trout": {
        "best_months": [3, 4, 5, 6, 9, 10, 11],
        "good_times": ["morning", "dusk"],
        "cloud_range": (40, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (5, 25),
        "good_wind_directions": ["SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (6, 18),
        "pressure_range": (995, 1022),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Fly fishing with buzzers, Diawl Bachs, nymphs, dries or small lures depending on fish depth.",
    },

    "Pike": {
        "best_months": [3, 4, 5, 9, 10, 11],
        "good_times": ["dawn", "morning", "dusk"],
        "cloud_range": (40, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (5, 25),
        "good_wind_directions": ["SW", "W", "NW"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (5, 18),
        "pressure_range": (995, 1020),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Lure fishing, deadbaiting or float fishing around weed beds, drop-offs, points and prey fish areas.",
    },

    "Perch": {
        "best_months": [5, 6, 7, 8, 9, 10],
        "good_times": ["dawn", "morning", "dusk"],
        "cloud_range": (30, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (3, 20),
        "good_wind_directions": ["SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (8, 22),
        "pressure_range": (995, 1025),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Small lures, drop-shot, worm, maggot feeder or float fishing near structure, weed edges and shoals of fry.",
    },

    "Roach": {
        "best_months": [4, 5, 6, 7, 8, 9, 10],
        "good_times": ["morning", "day", "dusk"],
        "cloud_range": (20, 90),
        "rain_range": (0, 2),
        "wind_speed_range": (0, 18),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (8, 24),
        "pressure_range": (1000, 1030),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Float fishing, pole fishing or light feeder tactics with maggots, casters, bread, hemp or small groundbait.",
    },

    "Bream": {
        "best_months": [5, 6, 7, 8, 9],
        "good_times": ["morning", "day", "dusk", "night"],
        "cloud_range": (30, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (3, 22),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (10, 24),
        "pressure_range": (998, 1028),
        "clarity": "slightly_coloured",
        "likes_moving_water": False,
        "method": "Feeder fishing with groundbait, pellets, corn, worm, maggot or method feeder tactics over a baited area.",
    },

    "Carp": {
        "best_months": [5, 6, 7, 8, 9],
        "good_times": ["dawn", "morning", "dusk", "night"],
        "cloud_range": (20, 100),
        "rain_range": (0, 2),
        "wind_speed_range": (3, 22),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (12, 26),
        "pressure_range": (998, 1028),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Ledgered boilies, pellets, corn, method feeder or surface fishing depending on fish activity.",
    },

    "Tench": {
        "best_months": [5, 6, 7, 8],
        "good_times": ["dawn", "morning", "dusk"],
        "cloud_range": (20, 90),
        "rain_range": (0, 2),
        "wind_speed_range": (0, 16),
        "good_wind_directions": ["S", "SW", "W"],
        "bad_wind_directions": ["E", "NE"],
        "temperature_range": (12, 24),
        "pressure_range": (1000, 1028),
        "clarity": "clear_to_slight_colour",
        "likes_moving_water": False,
        "method": "Float or feeder fishing near weed, lilies and soft bottom with corn, worm, maggots, pellets or small method feeders.",
    },
}